# Generated by Django 5.1.6 on 2026-04-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0002_rpgsession_crack_stage_rpgsession_stress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RpgCharacterImage',
        ),
        migrations.RemoveField(
            model_name='rpgchatlog',
            name='session',
        ),
        migrations.RemoveField(
            model_name='rpghypermemory',
            name='last_msg',
        ),
        migrations.RemoveField(
            model_name='rpgmessageembedding',
            name='chat_log',
        ),
        migrations.RemoveField(
            model_name='rpghypermemory',
            name='session',
        ),
        migrations.DeleteModel(
            name='RpgLorebook',
        ),
        migrations.RemoveField(
            model_name='rpgmessageembedding',
            name='session',
        ),
        migrations.RemoveField(
            model_name='rpgsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rpgstoryprogress',
            name='session',
        ),
        migrations.DeleteModel(
            name='RpgChatLog',
        ),
        migrations.DeleteModel(
            name='RpgHyperMemory',
        ),
        migrations.DeleteModel(
            name='RpgMessageEmbedding',
        ),
        migrations.DeleteModel(
            name='RpgSession',
        ),
        migrations.DeleteModel(
            name='RpgStoryProgress',
        ),
    ]
